#!/bin/sh
#
# Copyright (c) 2009-2013 Robert Nelson <robertcnelson@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Split out, so build_kernel.sh and build_deb.sh can share..

git="git am"
#git="git am --whitespace=fix"

if [ -f ${DIR}/system.sh ] ; then
	. ${DIR}/system.sh
fi

if [ "${RUN_BISECT}" ] ; then
	git="git apply"
fi

echo "Starting patch.sh"

git_add () {
	git add .
	git commit -a -m 'testing patchset'
}

cleanup () {
	git format-patch -${number} -o ${DIR}/patches/
	exit
}

arm () {
	echo "dir: arm"
	${git} "${DIR}/patches/arm/0001-deb-pkg-Simplify-architecture-matching-for-cross-bui.patch"
}

atmel_fixes () {
	echo "dir: atmel_fixes"
	${git} "${DIR}/patches/atmel_fixes/0001-ARM-at91-move-non-DT-Kconfig-to-Kconfig.non_dt.patch"
	${git} "${DIR}/patches/atmel_fixes/0002-ARM-at91-rename-board-dt-to-more-specific-name-board.patch"
	${git} "${DIR}/patches/atmel_fixes/0003-ARM-at91-renamme-rm9200-dt-file.patch"
}

atmel_SAMA5D3 () {
	echo "dir: atmel_SAMA5D3"
	${git} "${DIR}/patches/atmel_SAMA5D3/0001-ARM-at91-change-name-template-in-AT91_SOC_START-macr.patch"
	${git} "${DIR}/patches/atmel_SAMA5D3/0002-ARM-at91-add-AT91_SAM9_TIME-entry-to-select-at91sam9.patch"
	${git} "${DIR}/patches/atmel_SAMA5D3/0003-ARM-at91-introduce-the-core-type-choice-to-split-ARM.patch"
	${git} "${DIR}/patches/atmel_SAMA5D3/0004-ARM-at91-introduce-SAMA5-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5D3/0005-ARM-at91-dt-add-device-tree-files-for-SAMA5D3-family.patch"
	${git} "${DIR}/patches/atmel_SAMA5D3/0006-ARM-at91-add-defconfig-for-SAMA5.patch"
}

atmel_SAMA5 () {

	#Generated by:
	#git checkout v3.9 -b tmp
	#git pull --no-edit git://github.com/linux4sam/linux-at91.git linux-3.9-at91
	#git rebase v3.9
	#git format-patch -139 | grep 3.9
	#0001-Linux-3.9.patch
	#rm -rf *.patch
	#git format-patch -138 -o /opt/github/armv7_devel/patches/atmel_SAMA5/
	#git checkout master -f ; git branch -D tmp

	echo "dir: atmel_SAMA5"
	${git} "${DIR}/patches/atmel_SAMA5/0001-ARM-at91-move-non-DT-Kconfig-to-Kconfig.non_dt.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0002-ARM-at91-rename-board-dt-to-more-specific-name-board.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0003-ARM-at91-renamme-rm9200-dt-file.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0004-rtc-at91rm9200-add-DT-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0005-pcmcia-at91_cf-fix-gpio_get_value-in-at91_cf_get_sta.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0006-pcmcia-at91_cf-convert-to-dev_-print-functions.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0007-pcmcia-at91_cf-use-devm_-functions-for-allocations.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0008-pcmcia-at91_cf-clean-up-header-includes.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0009-pcmcia-at91_cf-add-support-for-DT.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0010-pcmcia-at91_cf-use-module_platform_driver_probe.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0011-pcmcia-trivial-at91_cf-fix-checkpatch-error.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0012-ARM-at91-dt-fix-macb-node-declaration.patch"
#3.9.1	${git} "${DIR}/patches/atmel_SAMA5/0013-ARM-at91-trivial-typos-in-compatible-property.patch"
#3.9.1	${git} "${DIR}/patches/atmel_SAMA5/0014-ARM-at91-trivial-fix-model-name-for-SAM9G15-EK.patch"
#3.9.1	${git} "${DIR}/patches/atmel_SAMA5/0015-ARM-at91-remove-partial-parameter-in-bootargs-for-at.patch"
#3.9.1	${git} "${DIR}/patches/atmel_SAMA5/0016-ARM-at91-Fix-typo-in-restart-code-panic-message.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0017-ARM-at91-change-name-template-in-AT91_SOC_START-macr.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0018-ARM-at91-add-AT91_SAM9_TIME-entry-to-select-at91sam9.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0019-ARM-at91-introduce-the-core-type-choice-to-split-ARM.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0020-ARM-at91-introduce-SAMA5-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0021-ARM-at91-dt-add-device-tree-files-for-SAMA5D3-family.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0022-ARM-at91-add-defconfig-for-SAMA5.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0023-ARM-at91-dt-at91sam9x5-add-i2c-pinctrl.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0024-ARM-at91-dt-at91sam9x5-add-i2c-gpio-pinctrl.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0025-ARM-at91-add-TWI-bindings-to-RM9200-DT.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0026-ARM-at91-add-pinctrl-nodes-to-i2c-gpio-on-RM92000-DT.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0027-ARM-at91-add-MPA-1600-DT-board.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0028-ARM-at91-dt-gpio-keys-remove-address-cells-and-size-.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0029-ARM-at91-at91sam9x5ek-i2c1-and-i2c2-conflict-with-ma.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0030-ARM-at91-at91sam9x5cm-add-1-wire-chip-on-CM-board.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0031-ARM-at91-at91sam9x5-add-RTC-node.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0032-ARM-at91-add-Acme-Systems-Aria-G25-board.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0033-ARM-at91-dts-add-adc-resolution-stuff.patch"
#3.9.1	${git} "${DIR}/patches/atmel_SAMA5/0034-ARM-at91-at91sam9260.dtsi-fix-u-s-art-pinctrl-encodi.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0035-ARM-at91-remove-unused-dbgu_readl-macro.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0036-ARM-at91-setup-fix-trivial-typos.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0037-ARM-at91-remove-trailing-semicolon-from-macros.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0038-dma-Remove-erroneous-__exit-and-__exit_p-references.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0039-at_hdmac-move-to-generic-DMA-binding.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0040-ARM-at91-dts-set-dma-cells-to-the-correct-value.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0041-i2c-at91-convert-to-dma_request_slave_channel_compat.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0042-mci-at91-convert-to-dma_request_slave_channel_compat.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0043-input-atmel_tsadcc-add-support-for-ARCH_AT91SAM9X5.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0044-input-atmel_tsadcc-add-touch-screen-pressure-measure.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0045-input-atmel_tsadcc-enable-touchscreen-averaging-and-.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0046-input-atmel_tsadcc-add-ACR-register-and-change-trigg.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0047-AT91-input-atmel_tsadcc-rework-irq-infrastructure-an.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0048-input-at91-add-tsadcc_data-for-9x5.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0049-input-at91-add-dt-support-for-atmel-touch-screen-adc.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0050-crypto-add-atmel-test-driver.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0051-can-at91_can-add-dt-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0052-MTD-atmel_nand-add-9x5-to-list-of-SoC-with-DMA.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0053-MTD-atmel_nand-POI-fall-back-is-not-an-issue-change-.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0054-MTD-atmel_nand-add-9n12-to-list-of-SoC-with-DMA.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0055-mtd-atmel_nand-add-4k-page-nand-flash-support-for-PM.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0056-mtd-atmel_nand-incease-the-chip_delay-time-tR-for-su.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0057-mtd-atmel_nand-fix-the-compile-error-which-miss-labe.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0058-MTD-atmel_nand-use-devm_xxx-gpio-kzalloc-gpio-and-io.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0059-MTD-atmel_nand-add-sama5d3-to-cpu_has_dma-function.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0060-atmel_nand-add-nand-flash-controller-NFC-definitions.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0061-atmel_nand-add-Nand-Flash-Controller-NFC-resources-a.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0062-atmel_nand-nfc-enable-NFC-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0063-atmel_nand-nfc-enable-read-operation-via-nfc-sram.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0064-atmel_nand-replace-pmecc-enable-code-with-one-functi.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0065-atmel_nand-enable-write-page-function-with-nfc-sram-.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0066-atmel_nand-can-switch-the-sram-banks.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0067-atmel_nand-nfc-enable-dma-for-page-read-with-nfc-sra.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0068-atmel_nand-add-dma-operation-for-write-via-NFC-sram.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0069-atmel_nand-nfc-add-interrupt-definitions.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0070-atmel_nand-add-dummy-interrupt-handler.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0071-atmel_nand-nfc-use-interrupt-instead-of-pooling-the-.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0072-ARM-at91-sama5d34ek.dts-remove-not-needed-compatibil.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0073-ARM-at91-change-Unknown-qualifier-SoC-subtype-handli.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0074-ARM-at91-suspend-both-memory-controllers-on-at91sam9.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0075-ARM-at91-dts-add-i2c-dma-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0076-ARM-at91-dts-add-MCI-DMA-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0077-ARM-at91-sama5d3-reduce-TWI-internal-clock-frequency.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0078-Input-atmel_tsadcc-fix-compilation-as-a-module.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0079-ARM-at91-add-Acme-Systems-Fox-G20-board.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0080-ARM-at91-at91-ariag25.dts-UART0-1-nodes-are-disabled.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0081-ARM-at91-at91sam9x5.dtsi-add-UART0-1-nodes.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0082-ARM-at91-at91-ariag25.dts-add-RTC-node.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0083-ARM-at91-at91sam9x5-RTC-is-not-compatible-with-at91r.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0084-spi-spi-atmel-detect-the-capabilities-of-SPI-core-by.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0085-spi-spi-atmel-add-support-transfer-on-CS1-2-3-not-on.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0086-spi-spi-atmel-call-unmapping-on-transfers-buffers.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0087-spi-spi-atmel-status-information-passed-through-cont.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0088-spi-atmel-fix-speed_hz-check-in-atmel_spi_transfer.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0089-spi-spi-atmel-add-physical-base-address.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0090-spi-spi-atmel-add-flag-to-controller-data-for-lock-o.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0091-spi-spi-atmel-add-dmaengine-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0092-spi-spi-atmel-BUG-fix-doesn-support-16-bits-transfer.patch"
#3.9.1	${git} "${DIR}/patches/atmel_SAMA5/0093-mmc-atmel-mci-pio-hang-on-block-errors.patch"
#3.9.1	${git} "${DIR}/patches/atmel_SAMA5/0094-mmc-at91-avr32-atmel-mci-fix-DMA-channel-leak-on-mod.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0095-mmc-atmel-mci-remove-include-mach-cpu.h.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0096-i2c-at91-Use-of_match_ptr-macro.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0097-ARM-AT91SAM9G45-same-platform-data-structure-for-all.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0098-crypto-atmel-sha-add-support-for-latest-release-of-t.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0099-crypto-atmel-tdes-add-support-for-latest-release-of-.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0100-crypto-atmel-aes-add-support-for-latest-release-of-t.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0101-dmaengine-at_hdmac-trivial-correct-typo-in-comment.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0102-dmaengine-at_hdmac-extend-hardware-handshaking-inter.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0103-dmaengine-at_hdmac-trivial-rearrange-CFG-register-bi.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0104-drivers-video-use-module_platform_driver_probe.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0105-video-atmel_lcdfb-add-support-for-AT91SAM9x5.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0106-video-atmel_lcdfb-The-output-bpp-should-not-change-a.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0107-video-atmelfb-initially-split-atmelfb-into-a-driver-.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0108-video-atmelfb-refactor-core-setup.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0109-video-atmelfb-refactor-start-stop.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0110-video-atmelfb-refactor-isr.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0111-video-atmelfb-refactor-backlight-routines.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0112-video-atmelfb-refactor-dma_update.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0113-video-atmelfb-refactor-LUT.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0114-video-atmelfb-refactor-limit_screeninfo.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0115-arm-at91-refactor-lcdc-includes.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0116-video-atmel_hlcdfb-add-new-driver.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0117-WIP-add-clut-resource.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0118-video-atmel_lcdfb-HLCD-modifications.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0119-atmel_lcdfb-change-pixel-clock-ratio-calculation.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0120-video-atmel_lcdfb-protect-bl_power-with-CONFIG_BACKL.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0121-video-atmel_lcdfb-adapt-to-all-IP-configurations.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0122-video-atmel_hlcdfb-add-second-overlay-support.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0123-video-atmel_hlcdfb-increase-the-base-layer-AHB-burst.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0124-video-atmel_hlcdfb-don-t-read-a-write-only-register.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0125-video-atmel_hlcdfb-don-t-wait-when-going-to-suspend.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0126-video-atmel_hlcdfb-now-suspend-resume-is-managed-onl.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0127-drivers-video-atmel_hlcdfb.c-fix-bad-timing-configur.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0128-drivers-video-atmel_hlcdfb.c-Remove-bad-default-conf.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0129-video-atmel_lcdfb-add-error-msg-when-out-of-memory.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0130-video-atmel_lcdfb-remove-duplicated-include.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0131-video-atmel_lcdfb-add-pinctrl.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0132-video-atmel-lcd-only-request-the-pinctrl-once.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0133-video-atmel_lcdfb-move-platform-data-to-new-header-l.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0134-drivers-video-atmel_lcdfb.c-fix-error-return-code.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0135-ARM-at91-add-LCD-device-and-overlays-in-DT-board.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0136-Change-internal-SRAM-memory-type-to-MT_MEMORY_SO.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0137-Input-atmel_tsadcc-remove-__devinit.patch"
	${git} "${DIR}/patches/atmel_SAMA5/0138-enable-SAMA5D3-support-in-touch-screen-adc-controlle.patch"
}

arm
atmel_SAMA5
#atmel_fixes
#atmel_SAMA5D3

echo "patch.sh ran successful"
